[package]
name = "cargo-cala"
version = "0.0.1"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"
license = "MIT / BSL-1.0"
documentation = "https://libcala.github.io/tutorials"
repository = "https://github.com/libcala/cargo-cala"
readme = "README.md"
description = "Cargo plugin for testing & building release packages that depend on cala and/or wasm."

[dependencies]
actix-web = "2.0"
actix-files = "0.1"
walrus = "0.15"
inotify = "0.7"
