[package]
name = "cargo-cala"
version = "0.0.1"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
actix-files = "0.1"
walrus = "0.14"
inotify = "0.7"
