[package]
name = "cargo-cala"
version = "0.0.1"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"
license = "MIT / BSL-1.0"
documentation = "https://libcala.github.io/tutorials"
repository = "https://github.com/libcala/cargo-cala"
readme = "README.md"
description = "A cargo plugin that makes cargo generate release packages instead of binaries."

[dependencies]
inotify = "0.8"
walrus = "0.16"
pasts = "0.3"
cala_web = { path = "../cala_web" }
