# ran-slat [ https://github.com/aldarons-tech/ran-slat ]

name = "_Demo-_GSP ( _Ran\Slat )"
comment = "_Demo:Packager-_Software-Graphical"

# TODO: Create .toml files for all of these languages
#
# ["ab", "¿¿¿??? {Abkhaz}"],
# ["aa", "¿¿¿??? {Afar}"],
# ["af", "{Afrikaans}"],
# ["ak", "{Akan}"],
# ["sq", "{Albanian}"],
# ["am", "{Amharic}"],
# ["ar", "{Arabic}"],
# ["an", "{Aragonese}"],
# ["hy", "{Armenian}"],
# ["as", "{Assamese}"],
# ["av", "{Avaric}"],
# ["ae", "{Avestan}"],
# ["ay", "{Aymara}"],
# ["az", "{Azerbaijani}"],
# ["bm", "{Bambara}"],
# ["ba", "{Bashkir}"],
# ["eu", "{Basque}"],
# ["be", "{Belarusian}"],
# ["bh", "{Bihari}"],
# ["bi", "{Bislama}"],
# ["bs", "{Bosnian}"],
# ["br", "{Breton}"],
# ["bg", "{Bulgarian}"],
# ["my", "{Burmese}"],
# ["ca", "{Catalan}"],
# ["ch", "{Chamorro}"],
# ["ce", "{Chechen}"],
# ["ny", "{Chichewa}"],
# ["cv", "{Chuvash}"],
# ["kw", "{Cornish}"],
# ["co", "{Corsican}"],
# ["cr", "{Cree}"],
# ["hr", "{Croatian}"],
# ["cs", "{Czech}"],
# ["da", "{Danish}"],
# ["dv", "{Divehi}"],
# ["nl", "{Dutch}"],
# ["dz", "{Dzongkha}"],
# ["et", "{Estonian}"],
# ["ee", "{Ewe}"],
# ["fo", "{Faroese}"],
# ["fj", "{Fijian}"],
# ["fi", "{Finnish}"],
# ["ff", "{Fula}"],
# ["gl", "{Galician}"],
# ["ka", "{Georgian}"],
# ["el", "{Greek - Modern}"],
# ["gn", "{Guaraní}"],
# ["gu", "{Gujarati}"],
# ["ht", "{Haitian}"],
# ["ha", "{Hausa}"],
# ["he", "{Hebrew - Modern}"],
# ["hz", "{Herero}"],
# ["ho", "{Hiri Motu}"],
# ["hu", "{Hungarian}"],
# ["id", "{Indonesian}"],
# ["ga", "{Irish}"],
# ["ig", "{Igbo}"],
# ["ik", "{Inupiaq}"],
# ["io", "{Ido}"],
# ["is", "{Icelandic}"],
# ["jv", "{Javanese}"],
# ["kl", "{Kalaallisut}"],
# ["kn", "{Kannada}"],
# ["kr", "{Kanuri}"],
# ["ks", "{Kashmiri}"],
# ["kk", "{Kazakh}"],
# ["km", "{Khmer}"],
# ["ki", "{Kikuyu}"],
# ["rw", "{Kinyarwanda}"],
# ["ky", "{Kyrgyz}"],
# ["kv", "{Komi}"],
# ["kg", "{Kongo}"],
# ["ko", "{Korean}"],
# ["ku", "{Kurdish}"],
# ["kj", "{Kwanyama}"],
# ["la", "{Latin}"],
# ["lb", "{Luxembourgish}"],
# ["lg", "{Ganda}"],
# ["li", "{Limburgish}"],
# ["ln", "{Lingala}"],
# ["lo", "{Lao}"],
# ["lt", "{Lithuanian}"],
# ["lu", "{Luba-Katanga}"],
# ["lv", "{Latvian}"],
# ["gv", "{Manx}"],
# ["mk", "{Macedonian}"],
# ["mg", "{Malagasy}"],
# ["ms", "{Malay}"],
# ["ml", "{Malayalam}"],
# ["mt", "{Maltese}"],
# ["mi", "{Māori}"],
# ["mr", "{Marāṭhī}"],
# ["mh", "{Marshallese}"],
# ["mn", "{Mongolian}"],
# ["na", "{Nauruan}"],
# ["nv", "{Navajo}"],
# ["nd", "{Northern Ndebele}"],
# ["ne", "{Nepali}"],
# ["ng", "{Ndonga}"],
# ["nb", "{Norwegian Bokmål}"],
# ["nn", "{Norwegian Nynorsk}"],
# ["no", "{Norwegian}"],
# ["ii", "{Nuosu}"],
# ["nr", "{Southern Ndebele}"],
# ["oc", "{Occitan}"],
# ["oj", "{Ojibwe}"],
# ["cu", "{Church Slavonic / Old Bulgarian}"],
# ["om", "{Oromo}"],
# ["or", "{Oriya}"],
# ["os", "{Ossetian}"],
# ["pa", "{(Eastern) Punjabi}"],
# ["pi", "{Pāli}"],
# ["fa", "{Persian}"],
# ["pl", "{Polish}"],
# ["ps", "{Pashto}"],
# ["pt", "{Portuguese}"],
# ["qu", "{Quechua}"],
# ["rm", "{Romansh}"],
# ["rn", "{Kirundi}"],
# ["ro", "{Romanian}"],
# ["ru", "{Russian}"],
# ["sa", "{Sanskrit (Saṁskṛta)}"],
# ["sc", "{Sardinian}"],
# ["sd", "{Sindhi}"],
# ["se", "{Northern Sami}"],
# ["sm", "{Samoan}"],
# ["sg", "{Sango}"],
# ["sr", "{Serbian}"],
# ["gd", "{Scottish Gaelic}"],
# ["sn", "{Shona}"],
# ["si", "{Sinhalese}"],
# ["sk", "{Slovak}"],
# ["sl", "{Slovene}"],
# ["so", "{Somali}"],
# ["st", "{Southern Sotho}"],
# ["su", "{Sundanese}"],
# ["sw", "{Swahili}"],
# ["ss", "{Swati}"],
# ["sv", "{Swedish}"],
# ["ta", "{Tamil}"],
# ["tg", "{Tajik}"],
# ["th", "{Thai}"],
# ["ti", "{Tigrinya}"],
# ["bo", "{Tibetan Standard}"],
# ["tk", "{Turkmen}"],
# ["tl", "{Tagalog}"],
# ["tn", "{Tswana}"],
# ["to", "{Tonga}"],
# ["tr", "{Turkish}"],
# ["ts", "{Tsonga}"],
# ["tt", "{Tatar}"],
# ["tw", "{Twi}"],
# ["ty", "{Tahitian}"],
# ["ug", "{Uyghur}"],
# ["uk", "{Ukrainian}"],
# ["ur", "{Urdu}"],
# ["uz", "{Uzbek}"],
# ["ve", "{Venda}"],
# ["vi", "{Vietnamese}"],
# ["wa", "{Walloon}"],
# ["cy", "{Welsh}"],
# ["wo", "{Wolof}"],
# ["fy", "{Western Frisian}"],
# ["xh", "{Xhosa}"],
# ["yi", "{Yiddish}"],
# ["yo", "{Yoruba}"],
# ["za", "{Zhuang}"],
# ["zu", "{Zulu}"],
# ["eo", "(Esperanto)"],
# ["hl", "(Hylian)"],
# ["ia", "(Interlingua)"],
# ["ie", "(Interlingue)"],
# ["vo", "(Volapük)"],
